apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: demos.app.example.com
spec:
  group: app.example.com
  scope: Namespaced
  names:
    plural: demos
    singular: demo
    kind: Demo
    listKind: DemoList
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: integer
                image:
                  type: string
            status:
              type: object
      subresources:         # ✅ Correctly placed
        status: {}
