apiVersion: apps/v1
kind: Deployment
metadata:
  name: arun-dep
  labels:
    app: web
spec:
  replicas: {{ size }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: arun-con1
        image: {{ image }}
        ports:
        - containerPort: 8000

